___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [ ]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [3]:
import numpy as np
print (np.__version__, np.__config__)


1.19.2 <module 'numpy.__config__' from 'D:\\anaconda\\lib\\site-packages\\numpy\\__config__.py'>


Створити вектор з 10 елементів, заповнений одиницями:

In [6]:
A = np.ones(10)
A

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [11]:
A = np.arange(0, 11)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [25]:

x = np.zeros( (5, 5) )
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [28]:
q = np.random.random(20)
w = np.nonzero(q)


print(q, w)

[0.93984308 0.4955461  0.2038878  0.60729524 0.46171199 0.28660429
 0.58528311 0.91983183 0.28877409 0.964743   0.61957759 0.59665463
 0.27239816 0.19447403 0.19484915 0.15639434 0.77656117 0.07733549
 0.31945047 0.8718082 ] (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64))


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [37]:
r = np.random.random(20)
m = r.mean()
d = np.median(r)
x = np.std(r)
print("Середнє значення:", m,
      "Медіана:", d,
     "Стандартне відхилення:", x)

Середнє значення: 0.47500337311253527 Медіана: 0.5003747924278358 Стандартне відхилення: 0.31077836406665355


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [40]:
Z = np.dot(np.random.random((4,2)), np.random.random((2,2)))
print(Z)

[[0.15741448 0.10292742]
 [0.18305013 0.17656676]
 [0.8106     0.47597969]
 [0.22846502 0.38464423]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [50]:
Z = np.dot(np.random.random((4,2)), np.random.random((2,2)))

print(Z.ravel())

print(np.max(Z))

print(np.min(Z))


[0.59178286 0.42396011 0.86685224 0.91063983 1.47825988 1.23443707
 0.60469396 0.48124061]
1.4782598827231301
0.4239601135434816


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

Дано матрицю. Знайти ранг матриці:

In [45]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

rank = np.linalg.matrix_rank(a)

AttributeError: module 'numpy.linalg' has no attribute 'matrix'

Знайти визначник матриці:

In [44]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [46]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

np.linalg.eigh(a)

(array([-14.30540864,  -4.34740072,  23.65280936]),
 array([[ 0.15315575,  0.88160309,  0.44645191],
        [ 0.63674998, -0.43353159,  0.6376518 ],
        [-0.75570681, -0.18661821,  0.62775861]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [47]:
a = np.random.randint(0,10,50)

print(np.bincount(a).argmax())

3


Виведіть лише парні числа, що діляться на 5:

In [ ]:
a = np.random.randint(0,10,50)

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [54]:
import numpy as np

M1 = np.array([[2., 5.], [1., -10.]]) 
v1 = np.array([1., 3.])

np.linalg.solve(M1, v1)

array([ 1. , -0.2])